---
title: "R Notebook"
output: html_notebook
---



```{r packages, include=FALSE}
library(ISLR)
library(dplyr)
library(MASS)
library(class)
library(bootstrap)
library(boot)
library(broom)
library(glmnet)
library(coin)
library(rcompanion)
library(pls)
library(leaps)
library(splines)
```


## Exercise 2

### Problem 5

## Exercise 3

### Problem 8
```{r 8}
auto = Auto
auto = auto[,1:7]
plot(auto)
fit = lm(mpg~.+I(displacement^2)+I(horsepower^2) + I(weight^2), data=auto)
summary(fit)
```


### Problem 9

(a)
```{r 9a}
poly.fit = lm(nox~poly(dis,3), data=Boston)
summary(poly.fit)
xCurve = seq(1,12,length=1000)
xCurve = data.frame(xCurve)
colnames(xCurve) <- c("dis")
yCurve = predict(poly.fit, newdata=xCurve)
plot(Boston[,'dis'], Boston[,'nox'])
lines(xCurve[,'dis'], yCurve, col="red", lty=1, lwd = 2)
```

(b)
```{r 9b}
par(mfrow=c(2,2))
for(i in 1:10){
  poly.fit = lm(nox~poly(dis,i), data=Boston)
  #summary(poly.fit)
  xCurve = seq(1,12,length=1000)
  xCurve = data.frame(xCurve)
  colnames(xCurve) <- c("dis")
  yCurve = predict(poly.fit, newdata=xCurve)
  plot(Boston[,'dis'], Boston[,'nox'], main=paste0(i,"-Order Polynomial, RSS=", round(sum(resid(poly.fit)^2), digits=3)))
  lines(xCurve[,'dis'], yCurve, col="red", lty=1, lwd = 2)
}
```

(d)
```{r 9d}
help = bs(x=Boston$dis, df=4, knots = c(3))
disrange = range(Boston$dis)
dis.grid = seq(from=disrange[1], to=disrange[2], length=506)

spline.fit = lm(nox~bs(x=Boston$dis, df=4), data=Boston)
summary(spline.fit)
xCurve = seq(1,12,length=506)
xCurve = data.frame(xCurve)
colnames(xCurve) <- c("dis")
yCurve = predict.lm(spline.fit, newx=list(xCurve=xCurve), se=T)
plot(Boston$dis, Boston$nox)
lines(xCurve[,'dis'], yCurve$fit, col="red", lty=1, lwd = 2)
```











### Problem 10

(a)
```{r 10a}
idx = sample(1:length(College[,1]), floor(0.75*length(College[,1])))
college.train = College[idx,]
college.test = College[-idx,]
fit = lm(Outstate~1, data=college.train)
fit2 = fs.reg(college.train$Outstate, college.train)
summary(fit)
summary(fit2)
```






























